trigger:
  branches:
    include: [ "*" ] 
  tags:
    include: [ "*" ]
pool:
  vmImage: 'ubuntu-latest'

steps: 
  - task: Docker@2
    inputs:
      containerRegistry: 'Docker_Registry'
      repository: 'jithendar/workstation'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: '$(Build.BuildId)'
