apiVersion: apps/v1
kind: Deployment
metadata:
  name: workstation
  labels:
    app: workstation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workstation
  template:
    metadata:
      annotations:
        co.elastic.logs/enabled: "true"
        co.elastic.logs/json.keys_under_root: "true"
      labels:
        app: workstation
    spec:
      containers:
        - name: workstation
          image: jithendar/workstation:10.5
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: "mongodb://mongodb:27017/workstation"
            - name: REDIS_HOST
              value: redis-master
---
apiVersion: v1
kind: Service
metadata:
  name: workstation
spec:
  selector:
    app: workstation
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
